version: "3.8"

services:
  job-match-liquibase:
    container_name: job-match-liquibase
    image: liquibase/liquibase
    volumes:
      - ./liquibase/config/changelog.xml:/liquibase/changelog.xml
      - ./liquibase/scripts:/liquibase/scripts
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://job-match-postgres:5432/your_database
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: my_password
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.xml
    command: >
      sh -c "tail -f /dev/null"
    networks:
      - job-match-net

networks:
  job-match-net:
