# Generated by Django 4.2.11 on 2024-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_mobile_6f2369_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mobile', 'line_token'], name='users_mobile_c22544_idx'),
        ),
    ]
